### PR TITLE
Fixed infinite loop when server returns an error

### PR DESCRIPTION
**Pull request by josaphatim**
Any server side error makes sieve manager to do an infinite looping.

### CODE REVIEW

**Comment by kroky** [comment]
@josaphatim nice catch!

**Comment by marclaporte** [comment]
@josaphatim @kroky Is it worth releasing 1.0.2 for this?

**Comment by josaphatim** [comment]
> @josaphatim @kroky Is it worth releasing 1.0.2 for this?
@marclaporte Not! There is a another bug that must first be fixed. I’ll have a look at it during the day. Thanks.

**Comment by josaphatim** [comment]
@kroky

I just noticed that every script starts with the {numberOfOctects} which is considered by Henrique to be the literalException and then the script was supposed to continue to read the rest. The case that we could not handle is when an error comes from the server. The error comes with the form script_name_or_file: line 1: error: . Can I use this to stop the script? THANKS

**Comment by kroky** [comment]
@josaphatim sure, feel free to extend the error detection capabilities of this script.

**Pull request merged**
